name: Blade Bundle Check

on: [push]

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

jobs:
  bundle-check:
    name: Bundle Check
    runs-on: ubuntu-latest # nosemgrep: non-self-hosted-runner
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
      - name: Use Node v14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Setup Cache & Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile
      - name: Build Blade
        run: yarn build
        working-directory: packages/blade
      - name: Run Bundlewatch
        run: yarn bundlewatch
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
        working-directory: packages/blade

